import re
R = re.compile
I = re.I

EXTENDED_RULES = {
    'Analytics': {
        'Clicky': {'script_paths': [R(r'static\.getclicky\.com', I)], 'js_globals': ['clicky']},
        'GoSquared': {'script_paths': [R(r'gosquared\.com', I)], 'js_globals': ['_gs']},
        'Woopra': {'script_paths': [R(r'static\.woopra\.com', I)], 'js_globals': ['woopra']},
        'Pendo': {'script_paths': [R(r'pendo\.io', I)], 'js_globals': ['pendo']},
        'PostHog': {'script_paths': [R(r'posthog\.com', I)], 'js_globals': ['posthog']},
        'Chartbeat': {'script_paths': [R(r'static\.chartbeat\.com', I)], 'js_globals': ['_cb']},
        'Countly': {'script_paths': [R(r'countly', I)], 'js_globals': ['Countly']},
        'Kissmetrics': {'script_paths': [R(r'kissmetrics\.com', I)], 'js_globals': ['_kmq']},
        'Snowplow': {'script_paths': [R(r'snowplow', I)], 'js_globals': ['snowplow']},
        'Mouseflow': {'script_paths': [R(r'mouseflow\.com', I)], 'js_globals': ['mouseflow']},
        'Smartlook': {'script_paths': [R(r'smartlook\.com', I)], 'js_globals': ['smartlook']},
        'Cronitor RUM': {'script_paths': [R(r'rum\.cronitor\.io', I)]},
        'Pirsch': {'script_paths': [R(r'pirsch\.io', I)]},
        'Splitbee': {'script_paths': [R(r'splitbee\.io', I)]},
        'Simple Analytics': {'script_paths': [R(r'simpleanalytics\.com', I)]},
        'Umami': {'script_paths': [R(r'umami', I)]},
        'Keen IO': {'script_paths': [R(r'keen\.io', I)]},
        'Gauges': {'script_paths': [R(r'gaug\.es', I)]},
        'Indicative': {'script_paths': [R(r'indicative\.com', I)]},
        'Inspectlet': {'script_paths': [R(r'inspectlet\.com', I)]},
        'Adobe Analytics': {'script_paths': [R(r'omtrdc\.net', I)], 'js_globals': ['s_gi']},
        'Baidu Analytics': {'script_paths': [R(r'hm\.baidu\.com', I)], 'js_globals': ['_hmt']},
    },
    'E-commerce': {
        'Ikas': {'script_paths': [R(r'cdn\.myikas\.com', I), R(r'ikas', I)], 'headers': {'X-Ikas-Cache': R(r'.*', I)}},
    },
    'Web Framework': {
        'Sails.js': {'headers': {'X-Powered-By': R(r'Sails', I)}},
        'Hapi': {'headers': {'X-Powered-By': R(r'hapi', I)}},
        'Koa': {'headers': {'X-Powered-By': R(r'koa', I)}},
        'AdonisJS': {'headers': {'X-Powered-By': R(r'AdonisJS', I)}, 'cookies': [R(r'adonis-session')]},
        'NestJS': {'headers': {'X-Powered-By': R(r'NestJS', I)}},
        'Deno': {'headers': {'Server': R(r'deno', I)}},
        'Bun': {'headers': {'Server': R(r'bun', I)}},
        'CakePHP': {'headers': {'X-Powered-By': R(r'CakePHP', I)}, 'cookies': [R(r'CAKEPHP')]},
        'CodeIgniter': {'headers': {'X-Powered-By': R(r'CodeIgniter', I)}},
        'Yii': {'headers': {'X-Powered-By': R(r'Yii', I)}},
        'Zend': {'headers': {'X-Powered-By': R(r'Zend', I)}},
        'Lumen': {'headers': {'X-Powered-By': R(r'Lumen', I)}},
        'Slim': {'headers': {'X-Powered-By': R(r'Slim', I)}},
        'Phalcon': {'headers': {'X-Powered-By': R(r'Phalcon', I)}},
        'Grails': {'headers': {'X-Powered-By': R(r'Grails', I)}},
        'Wicket': {'headers': {'X-Powered-By': R(r'Wicket', I)}},
        'Tapestry': {'headers': {'X-Powered-By': R(r'Tapestry', I)}},
        'Sinatra': {'headers': {'X-Powered-By': R(r'Sinatra', I)}},
        'Hanami': {'headers': {'X-Powered-By': R(r'Hanami', I)}},
        'Padrino': {'headers': {'X-Powered-By': R(r'Padrino', I)}},
        'Gin': {'headers': {'X-Powered-By': R(r'Gin', I)}},
        'Echo': {'headers': {'X-Powered-By': R(r'Echo', I)}},
        'Fiber': {'headers': {'X-Powered-By': R(r'Fiber', I)}},
        'CherryPy': {'headers': {'Server': R(r'CherryPy', I)}},
        'Tornado': {'headers': {'Server': R(r'TornadoServer', I)}},
        'Bottle': {'headers': {'Server': R(r'Bottle', I)}},
        'Lucky': {'headers': {'Server': R(r'Lucky', I)}},
        'Actix Web': {'headers': {'Server': R(r'Actix', I)}},
        'Rocket': {'headers': {'Server': R(r'Rocket', I)}},
        'Symfony': {'headers': {'X-Debug-Token': R(r'.*'), 'X-Debug-Token-Link': R(r'.*')}, 'url_paths': [R(r'/_profiler/', I), R(r'/_wdt/', I)]},
        'FuelPHP': {'cookies': [R(r'fuelcid')]},
        'Play Framework': {'cookies': [R(r'PLAY_SESSION')]},
        'Pyramid': {'cookies': [R(r'_pyramid_')]},
        'Marko': {'html_attrs': [R(r'data-marko')], 'js_globals': ['__MARKO_RUNTIME__']},
        'Mithril': {'script_paths': [R(r'mithril', I)], 'js_globals': ['Mithril']},
        'Riot.js': {'script_paths': [R(r'riot[.\-]', I)], 'js_globals': ['riot']},
        'Inferno': {'js_globals': ['__INFERNO_DEVTOOLS_GLOBAL_HOOK__']},
        'Polymer': {'html_attrs': [R(r'is="custom-style"')], 'script_paths': [R(r'polymer', I)]},
        'Aurelia': {'html_attrs': [R(r'aurelia-app')], 'script_paths': [R(r'aurelia', I)]},
        'Meteor': {'js_globals': ['Meteor']},
        'Phoenix': {'js_globals': ['__phoenix__']},
        'Vaadin': {'script_paths': [R(r'VAADIN', I)]},
        'GWT': {'script_paths': [R(r'\.nocache\.js', I)]},
        'Fresh': {'html_attrs': [R(r'data-fresh-key')]},
        'Leptos': {'html_attrs': [R(r'data-hk')]},
        'Waku': {'script_paths': [R(r'waku', I)]},
    },
    'JS Library': {
        'Moment.js': {'js_globals': ['moment'], 'script_paths': [R(r'moment', I)]},
        'Day.js': {'js_globals': ['dayjs'], 'script_paths': [R(r'dayjs', I)]},
        'Luxon': {'script_paths': [R(r'luxon', I)]},
        'Underscore.js': {'script_paths': [R(r'underscore', I)]},
        'Lodash': {'script_paths': [R(r'lodash', I)]},
        'Swiper': {'script_paths': [R(r'swiper', I)], 'css_classes': [R(r'\bswiper-')]},
        'Immutable.js': {'script_paths': [R(r'immutable(?:\.min)?\.js', I), R(r'[/@]immutable@[\d.]+', I)]},
        'RxJS': {'script_paths': [R(r'rxjs', I)]},
        'PixiJS': {'js_globals': ['PIXI'], 'script_paths': [R(r'pixi(?:js)?(?:\.min)?\.js', I), R(r'[/@]pixi(?:js)?[@/]', I)]},
        'Fabric.js': {'js_globals': ['fabric'], 'script_paths': [R(r'fabric(?:\.min)?\.js(?:[?#]|$)', I), R(r'[/@]fabricjs[@/]', I)]},
        'Paper.js': {'js_globals': ['paper'], 'script_paths': [R(r'paper-core', I), R(r'paper-full', I)]},
        'Konva': {'js_globals': ['Konva'], 'script_paths': [R(r'konva', I)]},
        'p5.js': {'js_globals': ['p5'], 'script_paths': [R(r'p5\.min\.js', I)]},
        'Babylon.js': {'js_globals': ['BABYLON'], 'script_paths': [R(r'babylonjs', I)]},
        'Tone.js': {'js_globals': ['Tone'], 'script_paths': [R(r'tone(?:\.min)?\.js', I), R(r'/tone@', I)]},
        'Howler.js': {'js_globals': ['Howl'], 'script_paths': [R(r'howler', I)]},
        'Cropper.js': {'js_globals': ['Cropper'], 'script_paths': [R(r'cropper', I)]},
        'Dropzone': {'js_globals': ['Dropzone'], 'script_paths': [R(r'dropzone', I)]},
        'TinyMCE': {'js_globals': ['tinymce'], 'script_paths': [R(r'tinymce', I)]},
        'CKEditor': {'js_globals': ['CKEDITOR'], 'script_paths': [R(r'ckeditor', I)]},
        'Quill': {'js_globals': ['Quill'], 'script_paths': [R(r'quill', I)]},
        'CodeMirror': {'js_globals': ['CodeMirror'], 'script_paths': [R(r'codemirror', I)]},
        'Flatpickr': {'js_globals': ['flatpickr'], 'script_paths': [R(r'flatpickr', I)]},
        'FullCalendar': {'js_globals': ['FullCalendar'], 'script_paths': [R(r'fullcalendar', I)]},
        'DataTables': {'css_classes': [R(r'\bdataTables_')]},
        'Select2': {'script_paths': [R(r'select2', I)]},
        'Sortable.js': {'js_globals': ['Sortable'], 'script_paths': [R(r'Sortable', I)]},
        'Intro.js': {'js_globals': ['introJs'], 'script_paths': [R(r'introjs(?:\.min)?\.js', I), R(r'intro\.js[/@]', I), R(r'[/@]introjs[@/]', I)]},
        'NProgress': {'js_globals': ['NProgress'], 'script_paths': [R(r'(?<![a-zA-Z])nprogress', I)]},
        'Pace.js': {'js_globals': ['Pace'], 'script_paths': [R(r'pace(?:\.min)?\.js(?:[?#]|$)', I), R(r'[/@]pace[@/]', I)]},
        'ECharts': {'js_globals': ['echarts'], 'script_paths': [R(r'echarts', I)]},
        'Plotly.js': {'js_globals': ['Plotly'], 'script_paths': [R(r'plotly', I)]},
        'FusionCharts': {'js_globals': ['FusionCharts'], 'script_paths': [R(r'fusioncharts', I)]},
        'ZingChart': {'js_globals': ['zingchart'], 'script_paths': [R(r'zingchart', I)]},
        'C3.js': {'js_globals': ['c3'], 'script_paths': [R(r'c3\.min\.js', I)]},
        'Particles.js': {'js_globals': ['particlesJS'], 'script_paths': [R(r'particles', I)]},
        'tsParticles': {'js_globals': ['tsParticles'], 'script_paths': [R(r'tsparticles', I)]},
        'Typed.js': {'js_globals': ['Typed'], 'script_paths': [R(r'typed(?:\.min)?\.js(?:[?#]|$)', I), R(r'[/@]typed\.js[@/]', I)]},
        'CountUp.js': {'script_paths': [R(r'countup(?:\.min)?\.js', I)]},
        'Lenis': {'script_paths': [R(r'lenis(?:\.min)?\.js(?:[?#]|$)', I), R(r'[/@]lenis[@/]', I)]},
        'Barba.js': {'script_paths': [R(r'barba(?:\.min)?\.js(?:[?#]|$)', I), R(r'[/@]barba(?:js)?[@/]', I)]},
        'WaveSurfer.js': {'js_globals': ['WaveSurfer'], 'script_paths': [R(r'wavesurfer', I)]},
        'Handsontable': {'js_globals': ['Handsontable'], 'script_paths': [R(r'handsontable', I)]},
        'AG Grid': {'css_classes': [R(r'\bag-grid')]},
        'Tabulator': {'js_globals': ['Tabulator'], 'script_paths': [R(r'tabulator', I)]},
        'FilePond': {'css_classes': [R(r'\bfilepond')]},
        'Uppy': {'script_paths': [R(r'uppy', I)]},
        'ProseMirror': {'script_paths': [R(r'prosemirror', I)]},
        'Tiptap': {'script_paths': [R(r'tiptap', I)]},
        'Monaco Editor': {'script_paths': [R(r'monaco-editor', I)]},
        'Ace Editor': {'js_globals': ['ace'], 'script_paths': [R(r'ace-builds', I)]},
        'Notiflix': {'js_globals': ['Notiflix'], 'script_paths': [R(r'notiflix', I)]},
        'iziToast': {'script_paths': [R(r'iziToast', I)]},
        'Notyf': {'script_paths': [R(r'notyf', I)]},
        'Driver.js': {'script_paths': [R(r'driver\.js', I)]},
        'Shepherd.js': {'script_paths': [R(r'shepherd', I)]},
        'Cleave.js': {'script_paths': [R(r'cleave', I)]},
        'IMask.js': {'script_paths': [R(r'imask', I)]},
        'Inputmask': {'script_paths': [R(r'inputmask', I)]},
        'Tom Select': {'script_paths': [R(r'tom-select', I)]},
        'Choices.js': {'script_paths': [R(r'choices(?:\.min)?\.js', I), R(r'[/@]choices[@/]', I)]},
        'Velocity.js': {'js_globals': ['Velocity'], 'script_paths': [R(r'velocity', I)]},
        'Framer Motion': {'script_paths': [R(r'framer-motion', I)]},
        'Popmotion': {'script_paths': [R(r'popmotion', I)]},
        'Locomotive Scroll': {'html_attrs': [R(r'data-scroll-container')]},
        'vis.js': {'script_paths': [R(r'vis-network', I)]},
        'Cytoscape.js': {'js_globals': ['cytoscape'], 'script_paths': [R(r'cytoscape', I)]},
        'GoJS': {'script_paths': [R(r'gojs', I)]},
        'JointJS': {'script_paths': [R(r'jointjs', I)]},
        'Turbolinks': {'script_paths': [R(r'turbolinks', I)]},
        'Formik': {'script_paths': [R(r'formik', I)]},
        'React Hook Form': {'script_paths': [R(r'react-hook-form', I)]},
        'Zod': {'script_paths': [R(r'zod\.umd\.js', I)]},
        'Vanta.js': {'script_paths': [R(r'vanta', I)]},
        'Rough.js': {'script_paths': [R(r'rough\.min\.js', I)]},
        'Zdog': {'js_globals': ['Zdog'], 'script_paths': [R(r'zdog', I)]},
        'MATTER.js': {'js_globals': ['Matter'], 'script_paths': [R(r'matter', I)]},
        'A-Frame': {'html_attrs': [R(r'<a-scene'), R(r'<a-entity')], 'script_paths': [R(r'aframe\.min\.js', I)]},
        'Parsley.js': {'script_paths': [R(r'parsley', I)], 'html_attrs': [R(r'data-parsley')]},
    },
    'UI Framework': {
        'Headless UI': {'script_paths': [R(r'headlessui', I)]},
        'Flowbite': {'script_paths': [R(r'flowbite', I)]},
        'Naive UI': {'script_paths': [R(r'naive-ui', I)]},
        'Arco Design': {'script_paths': [R(r'arco-design', I)]},
        'TDesign': {'script_paths': [R(r'tdesign', I)]},
        'Park UI': {'script_paths': [R(r'park-ui', I)]},
        'NextUI': {'script_paths': [R(r'nextui', I)]},
        'Shoelace': {'html_attrs': [R(r'sl-button'), R(r'sl-input')]},
        'Ionic': {'html_attrs': [R(r'<ion-app'), R(r'<ion-content'), R(r'<ion-router')]},
        'Framework7': {'css_classes': [R(r'\bf7-')]},
        'Onsen UI': {'html_attrs': [R(r'<ons-page')], 'script_paths': [R(r'onsenui', I)]},
        'Keen UI': {'script_paths': [R(r'keen-ui', I)]},
        'Buefy': {'script_paths': [R(r'buefy', I)]},
        'BootstrapVue': {'script_paths': [R(r'bootstrap-vue', I)]},
        'Oruga': {'script_paths': [R(r'@oruga-ui', I), R(r'oruga(?:\.min)?\.js', I)]},
        'Vuesax': {'script_paths': [R(r'vuesax', I)]},
        'Varlet UI': {'script_paths': [R(r'varlet', I)]},
        'Xtend UI': {'script_paths': [R(r'xtendui', I)]},
        'Skeleton': {'script_paths': [R(r'skeleton(?:\.min)?\.css(?:[?#]|$)', I), R(r'[/@]skeleton[@/]', I)]},
        'Pico.css': {'script_paths': [R(r'pico(?:\.min)?\.css(?:[?#]|$)', I), R(r'@picocss/pico', I)]},
        'Open Props': {'script_paths': [R(r'open-props', I)]},
        'Lightning Design': {'script_paths': [R(r'lightning', I)]},
        'Carbon Design': {'script_paths': [R(r'carbon-components', I)]},
        'Spectrum': {'script_paths': [R(r'spectrum-css', I)]},
        'Primer CSS': {'script_paths': [R(r'primer', I)]},
    },
    'CDN': {
        'Azure CDN': {'headers': {'X-MSEdge-Ref': R(r'.*', I)}},
        'Google Cloud CDN': {'headers': {'X-GUploader-UploadID': R(r'.*', I)}},
        'ArvanCloud': {'headers': {'AR-PoweredBy': R(r'Arvan', I)}},
        'CacheFly': {'headers': {'Server': R(r'CacheFly', I)}},
        'Limelight': {'headers': {'Via': R(r'limelight', I)}},
        'Edgecast': {'headers': {'Server': R(r'ECAcc', I)}},
        'jsDelivr': {'script_paths': [R(r'cdn\.jsdelivr\.net', I)]},
        'cdnjs': {'script_paths': [R(r'cdnjs\.cloudflare\.com', I)]},
        'Statically': {'script_paths': [R(r'cdn\.statically\.io', I)]},
        'esm.sh': {'script_paths': [R(r'esm\.sh', I)]},
    },
    'PaaS/Hosting': {
        'Kinsta': {'headers': {'X-Kinsta-Cache': R(r'.*', I)}},
        'WP Engine': {'headers': {'X-WPE-Cached': R(r'.*', I)}},
        'Pantheon': {'headers': {'X-Pantheon-Styx-Hostname': R(r'.*', I)}},
        'Platform.sh': {'headers': {'X-Platform-Server': R(r'.*', I)}},
        'Pagely': {'headers': {'X-Powered-By': R(r'Starter', I)}},
        'Convox': {'headers': {'X-Powered-By': R(r'Convox', I)}},
        'Dokku': {'headers': {'X-Powered-By': R(r'Dokku', I)}},
        'Deta': {'script_paths': [R(r'deta\.dev', I)]},
        'PlanetScale': {'script_paths': [R(r'planetscale\.com', I)]},
        'Nhost': {'script_paths': [R(r'nhost\.run', I)]},
        'Back4App': {'script_paths': [R(r'back4app\.com', I)]},
        'Alibaba Cloud': {'headers': {'Server': R(r'Tengine', I)}},
        'Tencent Cloud': {'headers': {'Server': R(r'TSA', I)}},
        'Oracle Cloud': {'headers': {'opc-request-id': R(r'.*', I)}},
        'IBM Cloud': {'headers': {'X-Backside-Transport': R(r'.*', I)}},
        'Hetzner': {'headers': {'Server': R(r'Hetzner', I)}},
        'OVH': {'headers': {'X-IPLB-Instance': R(r'.*', I)}},
        'Linode': {'headers': {'Server': R(r'linode', I)}},
        'Vultr': {'headers': {'Server': R(r'vultr', I)}},
        'Scaleway': {'headers': {'X-Scaleway': R(r'.*', I)}},
        'UpCloud': {'headers': {'Server': R(r'UpCloud', I)}},
        'Fastcomet': {'headers': {'Server': R(r'FastComet', I)}},
        'GitHub': {'headers': {'Server': R(r'GitHub\.com', I), 'X-GitHub-Request-Id': R(r'.*', I)}},
    },
    'Web Server': {
        'Kestrel': {'headers': {'Server': R(r'Kestrel', I)}},
        'Jetty': {'headers': {'Server': R(r'Jetty', I)}},
        'Tomcat': {'headers': {'Server': R(r'Tomcat', I)}},
        'Cowboy': {'headers': {'Server': R(r'Cowboy', I)}},
        'Gunicorn': {'headers': {'Server': R(r'gunicorn', I)}},
        'Uvicorn': {'headers': {'Server': R(r'uvicorn', I)}},
        'Puma': {'headers': {'Server': R(r'Puma', I)}},
        'Unicorn': {'headers': {'Server': R(r'Unicorn', I)}},
        'Thin': {'headers': {'Server': R(r'thin', I)}},
        'WEBrick': {'headers': {'Server': R(r'WEBrick', I)}},
        'Phusion Passenger': {'headers': {'Server': R(r'Phusion Passenger', I)}},
        'H2O': {'headers': {'Server': R(r'h2o', I)}},
        'Hiawatha': {'headers': {'Server': R(r'Hiawatha', I)}},
        'Cherokee': {'headers': {'Server': R(r'Cherokee', I)}},
        'Lighttpd': {'headers': {'Server': R(r'lighttpd', I)}},
        'Boa': {'headers': {'Server': R(r'Boa', I)}},
        'Traefik': {'headers': {'Server': R(r'Traefik', I)}},
    },
    'Security': {
        'Imperva': {'headers': {'X-CDN': R(r'Imperva', I)}},
        'Sucuri WAF': {'headers': {'Server': R(r'Sucuri', I)}},
        'F5 BIG-IP': {'headers': {'Server': R(r'BigIP', I)}},
        'Barracuda': {'headers': {'Server': R(r'Barracuda', I)}},
        'DDoS-Guard': {'headers': {'Server': R(r'DDoS-Guard', I)}},
        'PerimeterX': {'headers': {'X-PX': R(r'.*', I)}},
        'Shape Security': {'headers': {'X-Shape': R(r'.*', I)}},
        'Reblaze': {'headers': {'Server': R(r'Reblaze', I)}},
        'Signal Sciences': {'headers': {'X-Sigsci-Tags': R(r'.*', I)}},
        'BitNinja': {'headers': {'X-BitNinja': R(r'.*', I)}},
        'Fortinet': {'headers': {'Server': R(r'FortiWeb', I)}},
        'Radware': {'headers': {'X-RDWR': R(r'.*', I)}},
        'Citrix ADC': {'headers': {'Via': R(r'NS-CACHE', I)}},
        'BotGuard': {'headers': {'X-BotGuard': R(r'.*', I)}},
        'DataDome': {'headers': {'X-DataDome': R(r'.*', I)}},
        'Human Security': {'headers': {'X-Human': R(r'.*', I)}},
        'Kasada': {'headers': {'X-Kasada': R(r'.*', I)}},
        'Netcraft': {'headers': {'Server': R(r'Netcraft', I)}},
        'SiteLock': {'headers': {'X-SiteLock': R(r'.*', I)}},
    },
    'Chat/Support': {
        'Olark': {'script_paths': [R(r'static\.olark\.com', I)], 'js_globals': ['olark']},
        'Comm100': {'script_paths': [R(r'comm100\.com', I)]},
        'Chatwoot': {'script_paths': [R(r'chatwoot', I)], 'js_globals': ['chatwootSettings']},
        'Gorgias': {'script_paths': [R(r'gorgias', I)], 'js_globals': ['GorgiasChat']},
        'Help Scout': {'script_paths': [R(r'beacon-v2\.helpscout\.net', I)], 'js_globals': ['Beacon']},
        'Kayako': {'script_paths': [R(r'kayako', I)]},
        'Chatra': {'script_paths': [R(r'call\.chatra\.io', I)], 'js_globals': ['ChatraID']},
        'JivoChat': {'script_paths': [R(r'code\.jivosite\.com', I)], 'js_globals': ['jivo_api']},
        'SmartSupp': {'script_paths': [R(r'smartsuppcdn\.com', I)], 'js_globals': ['smartsupp']},
        'Userlike': {'script_paths': [R(r'userlike', I)], 'js_globals': ['userlike']},
        'Acquire': {'script_paths': [R(r'acquire\.io', I)]},
        'Front': {'script_paths': [R(r'chat\.frontapp\.com', I)]},
        'Re:amaze': {'script_paths': [R(r'reamaze', I)]},
        'Papercups': {'script_paths': [R(r'papercups', I)]},
    },
    'Payment': {
        'Adyen': {'js_globals': ['AdyenCheckout']},
        'Mollie': {'script_paths': [R(r'mollie', I)]},
        'Razorpay': {'js_globals': ['Razorpay']},
        'Chargebee': {'script_paths': [R(r'chargebee', I)]},
        'Recurly': {'script_paths': [R(r'recurly', I)]},
        'FastSpring': {'script_paths': [R(r'fastspring', I)]},
        '2Checkout': {'script_paths': [R(r'2checkout', I)]},
        'Worldpay': {'script_paths': [R(r'worldpay', I)]},
        'Authorize.Net': {'script_paths': [R(r'authorize\.net', I)]},
        'CyberSource': {'script_paths': [R(r'cybersource', I)]},
        'BlueSnap': {'script_paths': [R(r'bluesnap', I)]},
        'GoCardless': {'script_paths': [R(r'gocardless', I)]},
        'Payoneer': {'script_paths': [R(r'payoneer', I)]},
        'Wise': {'script_paths': [R(r'wise\.com', I)]},
        'Affirm': {'script_paths': [R(r'affirm', I)]},
        'Sezzle': {'script_paths': [R(r'sezzle', I)]},
        'Zip': {'script_paths': [R(r'zip\.co/', I)]},
        'Clearpay': {'script_paths': [R(r'clearpay', I)]},
        'Tabby': {'script_paths': [R(r'tabby', I)]},
        'Tamara': {'script_paths': [R(r'tamara', I)]},
        'PayTR': {'script_paths': [R(r'paytr', I)]},
        'iyzico': {'script_paths': [R(r'iyzico', I)]},
    },
    'A/B Testing': {
        'Split.io': {'script_paths': [R(r'split\.io', I)]},
        'Kameleoon': {'script_paths': [R(r'kameleoon\.com', I)], 'js_globals': ['kameleoon']},
        'AB Tasty': {'script_paths': [R(r'abtasty\.com', I)], 'js_globals': ['ABTasty']},
        'Convert': {'script_paths': [R(r'convert\.com', I)]},
        'Dynamic Yield': {'script_paths': [R(r'dynamicyield\.com', I)], 'js_globals': ['DY']},
        'Statsig': {'script_paths': [R(r'statsig\.com', I)]},
        'GrowthBook': {'script_paths': [R(r'growthbook', I)]},
        'Unleash': {'script_paths': [R(r'unleash', I)]},
        'Flagship': {'script_paths': [R(r'flagship\.io', I)]},
        'Taplytics': {'script_paths': [R(r'taplytics\.com', I)]},
    },
    'Marketing': {
        'Drip': {'script_paths': [R(r'getdrip\.com', I)]},
        'Customer.io': {'script_paths': [R(r'customer\.io', I)]},
        'Brevo': {'script_paths': [R(r'sendinblue\.com', I)]},
        'Iterable': {'script_paths': [R(r'iterable\.com', I)]},
        'Ortto': {'script_paths': [R(r'ortto\.com', I)]},
        'Marketo': {'script_paths': [R(r'marketo', I)]},
        'Pardot': {'script_paths': [R(r'pardot\.com', I)]},
        'Eloqua': {'script_paths': [R(r'eloqua', I)]},
        'HubSpot': {'script_paths': [R(r'js\.hs-scripts\.com', I), R(r'js\.hubspot\.com', I)], 'js_globals': ['_hsq']},
        'Omnisend': {'script_paths': [R(r'omnisend\.com', I)]},
        'Privy': {'script_paths': [R(r'privy\.com', I)]},
        'OptinMonster': {'script_paths': [R(r'optinmonster\.com', I)]},
        'Sumo': {'script_paths': [R(r'[./]sumo\.com/', I), R(r'sumome\.com', I), R(r'/sumo/', I)]},
        'Hello Bar': {'script_paths': [R(r'hellobar\.com', I)]},
        'Sleeknote': {'script_paths': [R(r'sleeknote\.com', I)]},
        'Justuno': {'script_paths': [R(r'justuno\.com', I)]},
        'Wisepops': {'script_paths': [R(r'wisepops\.com', I)]},
        'OptiMonk': {'script_paths': [R(r'optimonk\.com', I)]},
        'Attentive': {'script_paths': [R(r'attentive\.com', I)]},
        'Postscript': {'script_paths': [R(r'postscript\.io', I)]},
        'SMSBump': {'script_paths': [R(r'smsbump', I)]},
        'Yotpo': {'script_paths': [R(r'yotpo\.com', I)]},
        'Stamped.io': {'script_paths': [R(r'stamped\.io', I)]},
        'Judge.me': {'script_paths': [R(r'judge\.me', I)]},
        'Loox': {'script_paths': [R(r'loox\.io', I)]},
        'Trustpilot': {'script_paths': [R(r'trustpilot\.com', I)]},
        'Reviews.io': {'script_paths': [R(r'reviews\.io', I)]},
        'Bazaarvoice': {'script_paths': [R(r'bazaarvoice\.com', I)]},
        'PowerReviews': {'script_paths': [R(r'powerreviews\.com', I)]},
    },
    'Cookie Consent': {
        'Iubenda': {'script_paths': [R(r'iubenda', I)]},
        'Quantcast Choice': {'script_paths': [R(r'quantcast', I)]},
        'Didomi': {'script_paths': [R(r'didomi', I)]},
        'Termly': {'script_paths': [R(r'termly', I)]},
        'Complianz': {'script_paths': [R(r'complianz', I)]},
        'GDPR Cookie Consent': {'script_paths': [R(r'moove_gdpr', I)]},
        'Cookie Notice': {'script_paths': [R(r'cookie-notice', I)]},
        'Cookie Script': {'script_paths': [R(r'cookie-script\.com', I)]},
        'Civic': {'script_paths': [R(r'civic\.com', I)]},
        'Klaro': {'script_paths': [R(r'klaro', I)]},
        'Consent Manager': {'script_paths': [R(r'consentmanager', I)]},
        'UniConsent': {'script_paths': [R(r'uniconsent', I)]},
        'Admiral': {'script_paths': [R(r'admiral', I)]},
    },
    'Monitoring': {
        'Airbrake': {'script_paths': [R(r'airbrake', I)], 'js_globals': ['airbrakeJs']},
        'Honeybadger': {'script_paths': [R(r'honeybadger', I)], 'js_globals': ['Honeybadger']},
        'TrackJS': {'script_paths': [R(r'trackjs\.com', I)], 'js_globals': ['TrackJS']},
        'Raygun': {'script_paths': [R(r'raygun', I)], 'js_globals': ['rg4js']},
        'Elastic APM': {'script_paths': [R(r'elastic-apm', I)], 'js_globals': ['elasticApm']},
        'Dynatrace': {'script_paths': [R(r'dynatrace', I)], 'js_globals': ['dtrum']},
        'AppDynamics': {'script_paths': [R(r'appdynamics', I)]},
        'SpeedCurve': {'script_paths': [R(r'speedcurve', I)]},
        'Calibre': {'script_paths': [R(r'calibreapp', I)]},
        'DebugBear': {'script_paths': [R(r'debugbear', I)]},
        'Catchpoint': {'script_paths': [R(r'catchpoint', I)]},
        'Pingdom': {'script_paths': [R(r'pingdom', I)]},
        'UptimeRobot': {'script_paths': [R(r'uptimerobot', I)]},
        'StatusPage': {'script_paths': [R(r'statuspage\.io', I)]},
    },
    'Tag Manager': {
        'Ensighten': {'script_paths': [R(r'ensighten', I)]},
        'Signal': {'script_paths': [R(r'[/.]signal\.co/', I)]},
        'CommandersAct': {'script_paths': [R(r'commandersact', I)]},
        'Matomo Tag Manager': {'script_paths': [R(r'matomo.*container', I)]},
        'Piwik PRO Tag Manager': {'script_paths': [R(r'piwik.*container', I)]},
    },
    'Build Tool': {
        'esbuild': {'js_globals': ['__esbuild']},
        'Rollup': {'script_paths': [R(r'rollup', I)]},
        'SWC': {'script_paths': [R(r'swc\.min\.js', I)]},
        'Snowpack': {'script_paths': [R(r'snowpack', I)]},
        'Gulp': {'script_paths': [R(r'gulp', I)]},
        'Grunt': {'script_paths': [R(r'grunt', I)]},
        'Browserify': {'script_paths': [R(r'browserify', I)]},
    },
    'State Management': {
        'Recoil': {'js_globals': ['__recoil']},
        'Jotai': {'js_globals': ['jotai']},
        'Valtio': {'js_globals': ['valtio']},
        'XState': {'js_globals': ['xstate']},
        'Effector': {'js_globals': ['effector']},
        'Vuex': {'js_globals': ['__VUEX__']},
        'Akita': {'js_globals': ['akita']},
        'NgRx': {'js_globals': ['ngrx']},
    },
    'Font Service': {
        'Fontsource': {'script_paths': [R(r'fontsource', I)]},
        'Bunny Fonts': {'script_paths': [R(r'fonts\.bunny\.net', I)]},
        'fonts.com': {'script_paths': [R(r'fast\.fonts\.net', I)]},
        'Fontdeck': {'script_paths': [R(r'fontdeck\.com', I)]},
        'Cloud.typography': {'script_paths': [R(r'cloud\.typography\.com', I)]},
        'Material Icons': {'script_paths': [R(r'fonts\.googleapis\.com.*Material', I)]},
        'Bootstrap Icons': {'script_paths': [R(r'bootstrap-icons', I)]},
        'Remix Icon': {'script_paths': [R(r'remixicon', I)]},
        'Heroicons': {'script_paths': [R(r'heroicons', I)]},
        'Lucide Icons': {'script_paths': [R(r'lucide', I)]},
        'Phosphor Icons': {'script_paths': [R(r'phosphor-icons', I)]},
        'Tabler Icons': {'script_paths': [R(r'tabler-icons', I)]},
        'Feather Icons': {'script_paths': [R(r'feather-icons', I)]},
        'Boxicons': {'script_paths': [R(r'boxicons', I)]},
        'Line Awesome': {'script_paths': [R(r'line-awesome', I)]},
        'Ionicons': {'script_paths': [R(r'ionicons', I)]},
        'Eva Icons': {'script_paths': [R(r'eva-icons', I)]},
        'Themify Icons': {'script_paths': [R(r'themify-icons', I)]},
    },
    'Programming Language': {
        'Go': {'headers': {'Server': R(r'^(Caddy|Gin|Echo|Fiber)\b', I)}},
        'Rust': {'headers': {'Server': R(r'(Actix|Rocket|axum)', I)}},
        'Elixir': {'headers': {'Server': R(r'(Cowboy|Bandit)', I)}},
        'Scala': {'headers': {'Server': R(r'(Akka|Play)', I)}},
        'Kotlin': {'headers': {'Server': R(r'(Ktor)', I)}},
        'Lua': {'headers': {'Server': R(r'(openresty|Kong)', I)}},
    },
    'Miscellaneous': {
        'WebSocket': {'script_paths': [R(r'sockjs', I), R(r'websocket', I)]},
        'Server-Sent Events': {'html_attrs': [R(r'text/event-stream')]},
        'Turbo': {'html_attrs': [R(r'data-turbo-frame')]},
        'LiveWire': {'script_paths': [R(r'livewire', I)]},
        'Inertia.js': {'script_paths': [R(r'inertia', I)]},
        'Unpoly': {'script_paths': [R(r'unpoly', I)]},
        'Hotwire': {'script_paths': [R(r'hotwire', I)]},
        'Swup': {'script_paths': [R(r'swup', I)]},
    },
    'Accessibility': {
        'axe-core': {'script_paths': [R(r'axe-core', I), R(r'axe\.min\.js', I)]},
        'Pa11y': {'script_paths': [R(r'pa11y', I)]},
        'WAVE': {'script_paths': [R(r'wave\.webaim\.org', I)]},
        'AccessiBe': {'script_paths': [R(r'accessibe', I)]},
        'UserWay': {'script_paths': [R(r'userway', I)]},
        'EqualWeb': {'script_paths': [R(r'equalweb', I)]},
        'AudioEye': {'script_paths': [R(r'audioeye', I)]},
        'TrustedSite': {'script_paths': [R(r'trustedsite', I)]},
        'Level Access': {'script_paths': [R(r'levelaccess', I)]},
        'Deque': {'script_paths': [R(r'deque\.com', I), R(r'deque-systems', I), R(r'axe-devtools', I)]},
        'Stark': {'script_paths': [R(r'stark', I)]},
        'Tenon': {'script_paths': [R(r'tenon', I)]},
        'Monsido': {'script_paths': [R(r'monsido', I)]},
    },
    'Search': {
        'Algolia': {'script_paths': [R(r'algoliasearch', I)], 'js_globals': ['algoliasearch']},
        'MeiliSearch': {'script_paths': [R(r'meilisearch', I)]},
        'Typesense': {'script_paths': [R(r'typesense', I)]},
        'Swiftype': {'script_paths': [R(r'swiftype\.com', I)], 'js_globals': ['Swiftype']},
        'Doofinder': {'script_paths': [R(r'doofinder\.com', I)]},
        'Searchspring': {'script_paths': [R(r'searchspring', I)]},
        'Klevu': {'script_paths': [R(r'klevu', I)]},
        'Constructor.io': {'script_paths': [R(r'constructor\.io', I)]},
        'SearchStax': {'script_paths': [R(r'searchstax', I)]},
        'Yext': {'script_paths': [R(r'yext', I)], 'js_globals': ['YEXT']},
        'AddSearch': {'script_paths': [R(r'addsearch\.com', I)]},
        'Fuse.js': {'js_globals': ['Fuse']},
        'Lunr.js': {'js_globals': ['lunr']},
        'FlexSearch': {'js_globals': ['FlexSearch']},
    },
    'Personalization': {
        'Nosto': {'script_paths': [R(r'nosto', I)]},
        'Clerk.io': {'script_paths': [R(r'clerk\.io', I)]},
        'Barilliance': {'script_paths': [R(r'barilliance', I)]},
        'RichRelevance': {'script_paths': [R(r'richrelevance', I)]},
        'Emarsys': {'script_paths': [R(r'emarsys', I)]},
        'Bloomreach': {'script_paths': [R(r'bloomreach', I)]},
        'Insider': {'script_paths': [R(r'useinsider\.com', I)]},
        'Braze': {'script_paths': [R(r'braze', I)]},
        'MoEngage': {'script_paths': [R(r'moengage', I)]},
        'Leanplum': {'script_paths': [R(r'leanplum', I)]},
        'OneSignal': {'script_paths': [R(r'onesignal', I)]},
        'Airship': {'script_paths': [R(r'urbanairship', I)]},
        'WebEngage': {'script_paths': [R(r'webengage', I)]},
        'CleverTap': {'script_paths': [R(r'clevertap', I)]},
        'Sailthru': {'script_paths': [R(r'sailthru', I)]},
        'Listrak': {'script_paths': [R(r'listrak', I)]},
    },
    'Social': {
        'Facebook SDK': {'js_globals': ['FB']},
        'Twitter Widgets': {'script_paths': [R(r'platform\.twitter\.com/widgets', I)]},
        'Instagram Embed': {'script_paths': [R(r'instagram\.com/embed', I)]},
        'YouTube Embed': {'script_paths': [R(r'youtube\.com/embed', I)]},
        'Vimeo Embed': {'script_paths': [R(r'player\.vimeo\.com', I)]},
        'TikTok Embed': {'script_paths': [R(r'tiktok\.com/embed', I)]},
        'Reddit Embed': {'script_paths': [R(r'embed\.reddit', I)]},
        'Disqus': {'js_globals': ['DISQUS']},
        'Giscus': {'script_paths': [R(r'giscus\.app', I)]},
        'Utterances': {'script_paths': [R(r'utteranc\.es', I)]},
        'ShareThis': {'script_paths': [R(r'sharethis\.com', I)]},
        'AddThis': {'script_paths': [R(r'addthis\.com', I)]},
        'AddToAny': {'script_paths': [R(r'addtoany\.com', I)]},
    },
    'Maps': {
        'Google Maps': {'script_paths': [R(r'maps\.googleapis\.com', I)], 'js_globals': ['google']},
        'Mapbox': {'script_paths': [R(r'mapbox', I)], 'js_globals': ['mapboxgl']},
        'OpenLayers': {'script_paths': [R(r'openlayers', I)], 'js_globals': ['ol']},
        'Here Maps': {'script_paths': [R(r'hereapi\.com', I)]},
        'TomTom Maps': {'script_paths': [R(r'tomtom\.com', I)]},
        'Carto': {'script_paths': [R(r'carto\.com', I)]},
    },
    'Authentication': {
        'Auth0': {'script_paths': [R(r'auth0\.com', I)]},
        'Okta': {'script_paths': [R(r'okta\.com', I)]},
        'Firebase Auth': {'script_paths': [R(r'firebaseauth', I)]},
        'Supabase Auth': {'script_paths': [R(r'supabase.*auth', I)]},
        'Clerk': {'script_paths': [R(r'clerk\.com', I)]},
        'Stytch': {'script_paths': [R(r'stytch\.com', I)]},
        'Magic': {'script_paths': [R(r'magic\.link', I)]},
        'Passage': {'script_paths': [R(r'passage\.id', I)]},
        'WorkOS': {'script_paths': [R(r'workos\.com', I)]},
        'FusionAuth': {'script_paths': [R(r'fusionauth', I)]},
        'Keycloak': {'script_paths': [R(r'keycloak', I)]},
        'Descope': {'script_paths': [R(r'descope', I)]},
        'SuperTokens': {'script_paths': [R(r'supertokens', I)]},
        'Ory': {'script_paths': [R(r'ory\.sh', I)]},
        'NextAuth.js': {'script_paths': [R(r'next-auth', I)]},
        'Lucia Auth': {'script_paths': [R(r'lucia', I)]},
    },
    'Backend Service': {
        'Firebase': {'script_paths': [R(r'firebase', I)]},
        'Supabase': {'script_paths': [R(r'supabase', I)]},
        'Appwrite': {'script_paths': [R(r'appwrite', I)]},
        'Convex': {'script_paths': [R(r'convex\.dev', I)]},
        'Hasura': {'script_paths': [R(r'hasura', I)]},
        'Fauna': {'script_paths': [R(r'fauna', I)]},
        'DynamoDB': {'script_paths': [R(r'dynamodb', I)]},
        'CockroachDB': {'script_paths': [R(r'cockroachdb', I)]},
    },
    'Realtime': {
        'Pushwoosh': {'script_paths': [R(r'pushwoosh\.com', I)]},
        'Firebase Cloud Messaging': {'script_paths': [R(r'firebase.*messaging', I)]},
        'Pusher': {'js_globals': ['Pusher']},
        'Ably': {'js_globals': ['Ably']},
        'PubNub': {'js_globals': ['PubNub']},
        'Sendbird': {'script_paths': [R(r'sendbird', I)]},
    },
    'Testing': {
        'Cypress': {'script_paths': [R(r'cypress', I)]},
        'Playwright': {'script_paths': [R(r'playwright', I)]},
        'Selenium': {'script_paths': [R(r'selenium', I)]},
        'BrowserStack': {'script_paths': [R(r'browserstack', I)]},
        'LambdaTest': {'script_paths': [R(r'lambdatest', I)]},
        'Percy': {'script_paths': [R(r'percy', I)]},
        'Chromatic': {'script_paths': [R(r'chromatic', I)]},
        'Storybook': {'script_paths': [R(r'storybook', I)]},
    },
    'DevOps': {
        'Docker': {'headers': {'Server': R(r'(docker|container)', I)}},
        'Kubernetes': {'headers': {'X-Kubernetes-Pf-Uid': R(r'.*', I)}},
    },
    'CMS': {
        'Notion': {'script_paths': [R(r'notion\.so', I), R(r'notion-static\.com', I), R(r'notionusercontent\.com', I)]},
        'Coda': {'script_paths': [R(r'coda\.io', I), R(r'[/@]coda[@/]', I)]},
        'Airtable': {'script_paths': [R(r'airtable', I)]},
        'Retool': {'script_paths': [R(r'retool', I)]},
        'Plasmic': {'script_paths': [R(r'plasmic', I)]},
        'Builder.io': {'script_paths': [R(r'builder\.io', I)]},
        'Stackbit': {'script_paths': [R(r'stackbit', I)]},
        'CloudCannon': {'script_paths': [R(r'cloudcannon', I)]},
        'Forestry': {'script_paths': [R(r'forestry', I)]},
        'TinaCMS': {'script_paths': [R(r'tinacms', I)]},
        'GraphCMS': {'script_paths': [R(r'graphcms', I)]},
        'Hygraph': {'script_paths': [R(r'hygraph', I)]},
        'Caisy': {'script_paths': [R(r'caisy', I)]},
        'Zesty.io': {'script_paths': [R(r'zesty', I)]},
        'Crownpeak': {'script_paths': [R(r'crownpeak', I)]},
    },
    'WordPress Plugin': {
        'Yoast SEO': {'script_paths': [R(r'yoast', I)]},
        'Rank Math': {'script_paths': [R(r'rank-math', I)]},
        'All in One SEO': {'script_paths': [R(r'aioseo', I)]},
        'Jetpack': {'script_paths': [R(r'jetpack', I), R(r'stats\.wp\.com', I)]},
        'Contact Form 7': {'script_paths': [R(r'contact-form-7', I)]},
        'Gravity Forms': {'script_paths': [R(r'gravityforms', I)]},
        'WPForms': {'script_paths': [R(r'wpforms', I)]},
        'Formidable Forms': {'script_paths': [R(r'formidable', I)]},
        'WP Rocket': {'script_paths': [R(r'wp-rocket', I)]},
        'W3 Total Cache': {'script_paths': [R(r'w3-total-cache', I)]},
        'WP Super Cache': {'script_paths': [R(r'wp-super-cache', I)]},
        'LiteSpeed Cache': {'script_paths': [R(r'litespeed', I)]},
        'Autoptimize': {'script_paths': [R(r'autoptimize', I)]},
        'WP Fastest Cache': {'script_paths': [R(r'wpfc', I)]},
        'Perfmatters': {'script_paths': [R(r'perfmatters', I)]},
        'Asset CleanUp': {'script_paths': [R(r'asset-cleanup', I)]},
        'WP Bakery': {'script_paths': [R(r'js_composer', I)]},
        'Beaver Builder': {'script_paths': [R(r'fl-builder', I)]},
        'Divi': {'script_paths': [R(r'divi-builder', I), R(r'/et-pb-', I), R(r'/divi/', I)], 'html_attrs': [R(r'\bet_pb_\w'), R(r'data-et-multi-view')]},
        'Oxygen Builder': {'script_paths': [R(r'oxygen-builder', I)]},
        'Bricks': {'script_paths': [R(r'bricks-builder', I)]},
        'Breakdance': {'script_paths': [R(r'breakdance', I)]},
        'Brizy': {'script_paths': [R(r'brizy', I)]},
        'GeneratePress': {'script_paths': [R(r'generatepress', I)]},
        'Astra': {'script_paths': [R(r'/themes/astra[/-]', I), R(r'astra-theme', I)]},
        'Kadence': {'script_paths': [R(r'kadence', I)]},
        'Neve': {'script_paths': [R(r'starter-starter', I)]},
        'OceanWP': {'script_paths': [R(r'oceanwp', I)]},
        'Avada': {'script_paths': [R(r'/themes/[Aa]vada[/-]', I), R(r'/fusion[-_]', I)]},
        'Enfold': {'script_paths': [R(r'enfold', I)]},
        'Flatsome': {'script_paths': [R(r'flatsome', I)]},
        'Porto': {'script_paths': [R(r'porto-theme', I)]},
        'Advanced Custom Fields': {'script_paths': [R(r'acf-field', I)]},
        'Pods': {'script_paths': [R(r'pods-framework', I)]},
        'Meta Box': {'script_paths': [R(r'meta-box', I)]},
        'Toolset': {'script_paths': [R(r'toolset', I)]},
        'BuddyPress': {'script_paths': [R(r'buddypress', I)]},
        'bbPress': {'script_paths': [R(r'bbpress', I)]},
        'LearnDash': {'script_paths': [R(r'learndash', I)]},
        'LifterLMS': {'script_paths': [R(r'lifterlms', I)]},
        'TutorLMS': {'script_paths': [R(r'tutor-lms', I)]},
        'MemberPress': {'script_paths': [R(r'memberpress', I)]},
        'Easy Digital Downloads': {'script_paths': [R(r'easy-digital-downloads', I)]},
        'AffiliateWP': {'script_paths': [R(r'affiliatewp', I)]},
        'MonsterInsights': {'script_paths': [R(r'monsterinsights', I)]},
        'UpdraftPlus': {'script_paths': [R(r'updraftplus', I)]},
        'Wordfence': {'script_paths': [R(r'wordfence', I)]},
        'Sucuri Security': {'script_paths': [R(r'sucuri', I)]},
        'iThemes Security': {'script_paths': [R(r'itsec', I)]},
        'All-in-One WP Migration': {'script_paths': [R(r'ai1wm', I)]},
        'Duplicator': {'script_paths': [R(r'duplicator', I)]},
        'WP Migrate': {'script_paths': [R(r'wp-migrate', I)]},
        'WPML': {'script_paths': [R(r'wpml', I)]},
        'Polylang': {'script_paths': [R(r'polylang', I)]},
        'TranslatePress': {'script_paths': [R(r'translatepress', I)]},
        'TablePress': {'script_paths': [R(r'tablepress', I)]},
        'WP Mail SMTP': {'script_paths': [R(r'wp-mail-smtp', I)]},
        'Redirection': {'script_paths': [R(r'redirection', I)]},
        'Smush': {'script_paths': [R(r'wp-smush', I)]},
        'ShortPixel': {'script_paths': [R(r'shortpixel', I)]},
        'Imagify': {'script_paths': [R(r'imagify', I)]},
        'WebP Express': {'script_paths': [R(r'webp-express', I)]},
    },
    'Shopify App': {
        'Shopify Flow': {'script_paths': [R(r'shopify-flow', I)]},
        'Oberlo': {'script_paths': [R(r'oberlo', I)]},
        'Privy Shopify': {'script_paths': [R(r'privy', I)]},
        'ReConvert': {'script_paths': [R(r'reconvert', I)]},
        'PageFly': {'script_paths': [R(r'pagefly', I)]},
        'GemPages': {'script_paths': [R(r'gempages', I)]},
        'Shogun': {'script_paths': [R(r'shogun', I)]},
        'Zipify': {'script_paths': [R(r'zipify', I)]},
        'Bold Commerce': {'script_paths': [R(r'bold\.co', I)]},
        'ReCharge': {'script_paths': [R(r'recharge', I)]},
        'Loop Returns': {'script_paths': [R(r'loop-returns', I)]},
        'Returnly': {'script_paths': [R(r'returnly', I)]},
        'AfterShip': {'script_paths': [R(r'aftership', I)]},
        'ShipStation': {'script_paths': [R(r'shipstation', I)]},
        'Shippo': {'script_paths': [R(r'shippo', I)]},
    },
    'Serverless': {
        'AWS Lambda': {'url_paths': [R(r'lambda-url\..+\.on\.aws', I), R(r'lambda\.amazonaws\.com', I)]},
        'Google Cloud Functions': {'script_paths': [R(r'cloudfunctions', I)]},
        'Azure Functions': {'script_paths': [R(r'azurewebsites', I)]},
        'Cloudflare Workers': {'script_paths': [R(r'workers\.dev', I)]},
        'Vercel Functions': {'url_paths': [R(r'\.vercel\.app/api/', I)]},
        'Netlify Functions': {'script_paths': [R(r'netlify.*functions', I)]},
        'Deno Deploy': {'script_paths': [R(r'deno\.dev', I)]},
        'Fly.io': {'script_paths': [R(r'fly\.dev', I)]},
        'Begin': {'script_paths': [R(r'begin\.com', I)]},
        'SST': {'script_paths': [R(r'sst\.dev', I)]},
    },
    'API Gateway': {
        'Kong': {'headers': {'Server': R(r'kong', I)}},
        'Tyk': {'headers': {'X-Tyk-Gateway': R(r'.*', I)}},
        'Apigee': {'headers': {'X-Apigee-Proxy': R(r'.*', I)}},
        'MuleSoft': {'headers': {'X-MULE': R(r'.*', I)}},
        'WSO2': {'headers': {'Server': R(r'WSO2', I)}},
        'Zuul': {'headers': {'X-Zuul-Service': R(r'.*', I)}},
    },
    'Caching': {
        'Redis': {'headers': {'X-Cache-Engine': R(r'redis', I)}},
        'Memcached': {'headers': {'X-Cache': R(r'memcached', I)}},
        'Squid': {'headers': {'Via': R(r'squid', I)}},
        'HAProxy': {'headers': {'Server': R(r'haproxy', I)}},
        'Litespeed Cache': {'headers': {'X-LiteSpeed-Cache': R(r'.*', I)}},
        'WP Super Cache Headers': {'headers': {'WP-Super-Cache': R(r'.*', I)}},
        'Batcache': {'headers': {'X-Batcache': R(r'.*', I)}},
    },
    'SEO': {
        'Schema.org': {'html_attrs': [R(r'schema\.org')]},
        'JSON-LD': {'html_attrs': [R(r'application/ld\+json')]},
        'Open Graph': {'html_attrs': [R(r'og:title')]},
        'Twitter Cards': {'html_attrs': [R(r'twitter:card')]},
        'hreflang': {'html_attrs': [R(r'hreflang')]},
        'Canonical': {'html_attrs': [R(r'rel="canonical"')]},
        'AMP Link': {'html_attrs': [R(r'amphtml')]},
        'Ahrefs': {'script_paths': [R(r'ahrefs', I)]},
        'SEMrush': {'script_paths': [R(r'semrush', I)]},
        'Moz': {'script_paths': [R(r'moz\.com', I)]},
        'Screaming Frog': {'script_paths': [R(r'screamingfrog', I)]},
        'BrightEdge': {'script_paths': [R(r'brightedge', I)]},
        'Conductor': {'script_paths': [R(r'conductor', I)]},
        'seoClarity': {'script_paths': [R(r'seoclarity', I)]},
        'Botify': {'script_paths': [R(r'botify', I)]},
        'DeepCrawl': {'script_paths': [R(r'deepcrawl', I)]},
        'ContentKing': {'script_paths': [R(r'contentkingapp', I)]},
    },
    'Advertising': {
        'Google Ads': {'script_paths': [R(r'googleads', I)], 'js_globals': ['google_ads']},
        'Google AdSense': {'script_paths': [R(r'pagead2\.googlesyndication\.com', I)], 'js_globals': ['adsbygoogle']},
        'DoubleClick': {'script_paths': [R(r'doubleclick\.net', I)]},
        'Amazon Ads': {'script_paths': [R(r'amazon-adsystem\.com', I)]},
        'Bing Ads': {'script_paths': [R(r'bat\.bing\.com', I)], 'js_globals': ['UET']},
        'Criteo': {'script_paths': [R(r'criteo', I)], 'js_globals': ['criteo_q']},
        'Taboola': {'script_paths': [R(r'taboola', I)], 'js_globals': ['_taboola']},
        'Outbrain': {'script_paths': [R(r'outbrain', I)], 'js_globals': ['OBR']},
        'Media.net': {'script_paths': [R(r'[/:]media\.net/', I)]},
        'PropellerAds': {'script_paths': [R(r'propellerads', I)]},
        'Ezoic': {'script_paths': [R(r'ezoic', I)]},
        'Mediavine': {'script_paths': [R(r'mediavine', I)]},
        'AdThrive': {'script_paths': [R(r'adthrive', I)]},
        'Raptive': {'script_paths': [R(r'raptive', I)]},
        'Monumetric': {'script_paths': [R(r'monumetric', I)]},
        'SHE Media': {'script_paths': [R(r'shemedia', I)]},
        'Carbon Ads': {'script_paths': [R(r'carbonads', I)]},
        'BuySellAds': {'script_paths': [R(r'buysellads', I)]},
        'AdRoll': {'script_paths': [R(r'adroll', I)], 'js_globals': ['adroll']},
        'Perfect Audience': {'script_paths': [R(r'perfectaudience', I)]},
        'Quantcast': {'script_paths': [R(r'quantcast', I)]},
        'TradeDesk': {'script_paths': [R(r'thetradedesk', I)]},
    },
    'Scheduling': {
        'Calendly': {'script_paths': [R(r'calendly\.com', I)]},
        'Cal.com': {'script_paths': [R(r'cal\.com', I)]},
        'Acuity': {'script_paths': [R(r'acuityscheduling', I)]},
        'Square Appointments': {'script_paths': [R(r'squareup', I)]},
        'SimplyBook': {'script_paths': [R(r'simplybook', I)]},
        'Setmore': {'script_paths': [R(r'setmore', I)]},
        'YouCanBook.me': {'script_paths': [R(r'youcanbook', I)]},
        'Doodle': {'script_paths': [R(r'doodle', I)]},
        'Bookafy': {'script_paths': [R(r'bookafy', I)]},
        'Appointlet': {'script_paths': [R(r'appointlet', I)]},
    },
    'Form Builder': {
        'Typeform': {'script_paths': [R(r'typeform', I)]},
        'JotForm': {'script_paths': [R(r'jotform', I)]},
        'Tally': {'script_paths': [R(r'tally\.so', I)]},
        'Paperform': {'script_paths': [R(r'paperform', I)]},
        'Formspree': {'script_paths': [R(r'formspree', I)]},
        'Netlify Forms': {'script_paths': [R(r'netlify.*form', I)]},
        'Basin': {'script_paths': [R(r'usebasin', I)]},
        'Getform': {'script_paths': [R(r'getform', I)]},
        'FormKeep': {'script_paths': [R(r'formkeep', I)]},
        'Kwes': {'script_paths': [R(r'kwes\.io', I)]},
        'FormSubmit': {'script_paths': [R(r'formsubmit', I)]},
        'Web3Forms': {'script_paths': [R(r'web3forms', I)]},
        'HeyForm': {'script_paths': [R(r'heyform', I)]},
    },
    'Translation': {
        'Crowdin': {'script_paths': [R(r'crowdin', I)]},
        'Lokalise': {'script_paths': [R(r'lokalise', I)]},
        'Transifex': {'script_paths': [R(r'transifex', I)]},
        'Phrase': {'script_paths': [R(r'phrase', I)]},
        'Weglot': {'script_paths': [R(r'weglot', I)]},
        'Locize': {'script_paths': [R(r'locize', I)]},
        'i18next': {'script_paths': [R(r'i18next', I)]},
        'FormatJS': {'script_paths': [R(r'formatjs', I)]},
        'LinguiJS': {'script_paths': [R(r'lingui', I)]},
        'Tolgee': {'script_paths': [R(r'tolgee', I)]},
    },
    'Headless Commerce': {
        'Commercetools': {'script_paths': [R(r'commercetools', I)]},
        'Elastic Path': {'script_paths': [R(r'elasticpath', I)]},
        'Fabric': {'script_paths': [R(r'fabric\.inc', I)]},
        'Nacelle': {'script_paths': [R(r'nacelle', I)]},
        'Chord': {'script_paths': [R(r'chord\.co', I)]},
        'Crystallize': {'script_paths': [R(r'crystallize', I)]},
        'BigCommerce Headless': {'script_paths': [R(r'bigcommerce.*graphql', I)]},
    },
    'Automation': {
        'Zapier': {'script_paths': [R(r'zapier\.com', I)]},
        'Make': {'script_paths': [R(r'make\.com/embed', I)]},
        'n8n': {'script_paths': [R(r'n8n\.io', I)]},
        'IFTTT': {'script_paths': [R(r'ifttt\.com', I)]},
        'Workato': {'script_paths': [R(r'workato\.com', I)]},
    },
    'Customer Data': {
        'mParticle': {'script_paths': [R(r'mparticle\.com', I)]},
        'Rudderstack': {'script_paths': [R(r'rudderstack\.com', I)]},
        'Tealium AudienceStream': {'script_paths': [R(r'tealium.*audiencestream', I)]},
        'Lytics': {'script_paths': [R(r'lytics\.io', I)]},
        'BlueConic': {'script_paths': [R(r'blueconic\.net', I)]},
        'Treasure Data': {'script_paths': [R(r'treasuredata\.com', I)]},
    },
}
